title:'01|風是甜的',
subtitle: '梁任宏',
size:'作品尺寸: 高398 x 長220 x 寬52（公分)',
material:'作品材質: 不鏽鋼、烤漆、培林',
content:'梁任宏受邀為各地各式節慶以及公共環境製作大型的戶外裝置，呈現出其多元精準的藝術樣貌。本次展出他的〈風是甜的〉，手持巨型的甜筒冰淇淋，色彩甜美討喜，任隨大自然的風動而擺動。在後站地下道的出口即能明顯地看到這件作品揮舞雙臂，就像是在歡迎旅客來到新竹。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,
orientationText:'No orientation',


title:'02|Mountain',
subtitle: 'Brendan Monroe',
size:'依現場空間而定',
material:'作品材質: 漆料',
content:'Brendan於2004年獲得Pasadena藝術中⼼的藝術學士學位，他培養出對科學、數學與物理的品味，他說：「我對世界的詮釋常根植於科學,再以雕刻與繪畫表現出來，而這是我喜歡的溝通方式。」他的創作非常多元化，從裝置藝術、繪畫、雕塑、布偶到玩具,各種作品都有⾃己的⾵格。這次他以獨特眼光選擇了後站的幾棟老屋牆面，對其進行美化的創作，吸引來往行人駐足。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'03|蕊之森',
subtitle: '有用主張設計x建築繁殖場',
size:'作品尺寸: 高600x長2500x深500（公分）',
material:'作品材質: 鐵、木、燈具',
content:'擁有台灣第一個科學園區的新竹，素有「台灣矽谷」之稱，因而令人直接聯想到科技與現代，城市裡面擁有高密度的古蹟和歷史建築，也有天然的自然環境，其中最有名的便是「風」。本作品以風動裝置為出發點，結合市花杜鵑花的花蕊樣態來發想，創造出令來往民眾能置身在「花蕊」之中的地景裝置。往後在此客運站接送或等待親友下車的民眾，將擁有美麗的「蕊之森」作為相約的meeting point。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'04|STRANGERS',
subtitle: 'STRØK/Anders Gjennestad',
size:'作品尺寸: 依現場空間而定',
material:'作品材質: 漆料 ',
content:'挪威街頭藝術家 Anders Gjennestad (也被稱為STRØK)，以創造逼真顛覆視覺的圖像聞名，善⽤多層次板模在不同材質表⾯創作出如攝影般寫實的畫作，板模都是依他自己所拍的照⽚再⼿工雕刻出來的。地點通常是在廢棄的⼯廠和房屋⽤影⼦為主題。他創作的人物都像是在一個沒有重⼒且時空靜止的狀態下並列。在客運巴士和駕駛們來往的路沖牆面上繪製他最擅長的人物剪影，與行道上的人們產生有趣的互動。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'05|聲光園地',
subtitle: '姚仲涵',
size:'作品尺寸: 依現場空間而定',
material:'作品材質: 戶外防水喇叭、防水燈光、電腦控制系統、洗牆燈',
content:'里民志工園地是存在我們各自的生活中非常具有地方特色的空間，藝術家姚仲涵提出「整點燈光秀」的概念，將傳統日光燈亮起瞬間的閃爍感，塑造出獨特的聲光美學。這件作品使用在地相關的歌曲，是讓民眾可以朗朗上口的旋律，將科技與在地情感的演出留存在我們的日常生活中。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'06|吹泡泡',
subtitle: '林建榮',
size:'作品尺寸: 設置範圍依現場空間而定',
material:'作品材質: PVC充氣、FRP',
content:'林建榮擅長結合燈泡與雕塑的創作，可愛的如兒童一樣圓胖的身材，頭上點亮著渾圓而溫暖光線的燈泡，是非常親人的設計。這些小人兒即將坐在後站停車場向新竹公園必經的牆面上，將民眾引導至地景藝術展的下一個重要基地。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'07|光譜原色時代',
subtitle: '蔡宜婷x沃手工作',
size:'作品尺寸: 依現場空間而定',
material:'作品材質: 水稜鏡、白光',
content:'光象徵真理，而發散美麗光彩的三稜鏡就像闡釋真理的心智。位於麗池畔，使用光透過三稜鏡能分散出七原色的原理，〈光譜原色時代〉設置數個大型三稜鏡在池畔，透過特定角度的安排，將一道一道的彩虹光束折射到水池面上，波光粼粼與彩色光線相互輝映。本件作品圍繞著湖畔料亭與水畔的草坡，用藝術設置將民眾留在美麗的。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'08|原來五百的家鄉在新竹',
subtitle: '陳浚豪',
size:'作品尺寸: 高300 x 長606 x 寬243（公分）',
material:'作品材質: 貨櫃、透明壓克力、玻璃珠、LED燈',
content:'計畫以新竹在地的玻璃珠材質作為創作元素,以點串成線, 線再構成面,面再構成立體的3D鈔票面額,如同層層的珠簾裝置在廿呎貨櫃 (計畫切除正面與兩個側面)之中,加上自然光的運用,讓珠簾彷若大塊假我 以文章的量化美感得以呈現在公共空間,在觀者的遠近觀察移動中,鈔票上的 圖像如群鹿、山頭、竹葉等將在具象與抽象之間轉換,期盼能創造了另一種材 質上互動性的視覺光譜。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,


title:'09|The Collector',
subtitle: 'HOTTEA',
size:'作品尺寸: 依現場空間而定',
material:'作品材質: 棉線、鐵(或鋼索)',
content:'明尼蘇達藝術家HOTTEA，擅⻑利⽤都市中的物件例如鐵絲網柵欄與異材質結合成⼀件作品，代表作就是以⽤彩色的毛線製作出美麗的幾何圖形。他的作品主要與透視有關，象徵著以不同的方法看這個世界，無論是字面上的或是作品所暗喻的意思。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,


title:'10|春雪後',
subtitle: '依現場空間而定 ',
size:'作品尺寸: 單個高50x長30x寬30（公分）共50個 ',
material:'作品材質: 竹',
content:'藝術家游文富的作品，以纖細的竹枝為主體，透過大量的身體勞動而完成巨型的地景藝術。這次選在新竹公園的環形舞台周圍，以白色竹枝插滿此一略為下凹的區域，像是剛下過春雪的美景，而當初春時節，現場種植在外圈的櫻花盛開，這裡將搖身變成紅白同心圓的舞台。家人親子好友前來遊玩的同時，穿梭其中，都成為這個名為〈春雪後〉的大型劇場的演員。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'11|千光景',
subtitle: '蔡坤霖',
size:'作品尺寸: 單個高50x長30x寬30（公分）共50個 ',
material:'作品材質: 2~3英吋硬質塑膠管 、燈光裝置',
content:'藝術家蔡坤霖擅長以塑膠管結合聲音裝置，在室內或戶外組裝大大小小可供民眾互動之作品。這次選在新竹公園旁靠公園路之樹林中架設數十組鑲嵌了透過田野調查收集而來的鄉鎮特色。外地民眾可以藉此作品了解新竹的文化風俗，在地居民則能重新認識家鄉的故事。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'12|Passing By',
subtitle: '蔡奇宏x沃手工作',
size:'作品尺寸:依現場空間而定',
material:'作品材質: LED燈、壓克力、金屬鐵件、電子零件',
content:'作品預計設置在新竹公園靠近公園路之樹林內，選擇設置在電箱上旁的安全圍欄上。半透明的壓克力燈光裝置，經過藝術家程式設計與電路控制，彩色的燈光變幻與參觀民眾產生互動的效果。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'13|新竹太郎',
subtitle: '林建志',
size:'作品尺寸: 高500 x 長200 x 寬150（公分）',
material:'作品材質: 玻璃、鐵、FRP',
content:'新竹市立動物園位於一九一六園區之內，為台灣歷史悠久之動物園，陪伴著多數新竹朋友成長，更承載著許多市民的共同記憶。而當藝術家林建志旗下的主角熊仔來到了新竹，變裝成台灣形象大使台灣黑熊，並邀約了動物園logo主角梅花鹿以及2016生肖動物猴仔一起組成了一支戰隊，希望在地朋友與前來新竹的遊客朋友一同率領他們，共同來守護著新竹的生態與社會環境，當個新竹太郎。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'14|時光旅行艙',
subtitle: '李承亮',
size:'作品尺寸: 高220 x 長600 x 寬170（公分）',
material:'作品材質: 彩色玻璃、黑鐵｀漆、木料',
content:'作為第二主題「歡樂派對」走向「電幻時刻」的重要節點，藝術家李承亮提出〈時光旅行艙〉，高於2公尺長6公尺的純鐵製旅行艙內，有木製的室內走道，行人可自由走入艙內，透過上方彩色玻璃向外看，藍天綠樹都染上了色彩，如同到了外太空，即將飛向充滿科幻感的「舞光十射」。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,

title:'15|裝置微光計畫：新竹孔廟',
subtitle: null,
size:'作品尺寸: 約80x23（公尺）',
material:'作品材質:電子裝置、雷射光、琉璃燈罩',
content:'莊志維近年致力於發展以戶外雷射光為主的大型光雕藝術，這次為新竹孔廟前廣場量身定制之〈裝置微光計畫：新竹孔廟〉於兩兩相對之路燈改裝琉璃燈罩，白天時刻陽光透過燈罩折射光線在鋪面上；而到了晚間，電子定時裝置開啟雷射光，舞動交錯劃破黑夜，讓寂靜的廣場也成了熱鬧的舞台。',
playing:false,
playPressing:false,
stopPressing:false,
outText:'Stop',
deviceHeight:deviceHeight,
deviceWidth:deviceWidth,
